# Generated by Django 5.1.3 on 2024-12-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gear", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lens",
            name="length",
            field=models.FloatField(default=0, verbose_name="Length (cm)"),
        ),
        migrations.AlterField(
            model_name="lens",
            name="max_aperture",
            field=models.FloatField(default=0, help_text="ex 2.8"),
        ),
        migrations.AlterField(
            model_name="lens",
            name="min_aperture",
            field=models.FloatField(default=0, help_text="ex 22"),
        ),
    ]
