# Generated by Django 5.1.3 on 2024-12-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gear", "0005_body_acquired_for_body_acquired_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="body",
            name="acquired_note",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
