# Generated by Django 5.1.3 on 2024-12-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gear", "0007_alter_body_acquired_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="body",
            name="acquired_on",
            field=models.DateField(blank=True),
        ),
    ]
