# Generated by Django 5.1.3 on 2024-12-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gear", "0009_alter_body_acquired_on_alter_body_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessory",
            name="acquired_for",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="accessory",
            name="acquired_note",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="accessory",
            name="acquired_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lens",
            name="acquired_for",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="lens",
            name="acquired_note",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="lens",
            name="acquired_on",
            field=models.DateField(blank=True, null=True),
        ),
    ]
