# Generated by Django 5.1.3 on 2024-12-04 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gear", "0013_body_wip_sheet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lens",
            name="angle",
        ),
    ]
