# Generated by Django 5.1.3 on 2024-12-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gear", "0014_remove_lens_angle"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessory",
            name="wip_sheet",
            field=models.BooleanField(default=True, help_text="Is this sheet still a WIP ?"),
        ),
        migrations.AddField(
            model_name="lens",
            name="wip_sheet",
            field=models.BooleanField(default=True, help_text="Is this sheet still a WIP ?"),
        ),
    ]
