# Generated by Django 5.1.3 on 2024-12-04 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gear", "0015_accessory_wip_sheet_lens_wip_sheet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="body",
            name="macro",
            field=models.BooleanField(default=False, verbose_name="Macro capable"),
        ),
        migrations.AlterField(
            model_name="lens",
            name="blades",
            field=models.BooleanField(default=False, verbose_name="Using blades"),
        ),
        migrations.AlterField(
            model_name="lens",
            name="macro",
            field=models.BooleanField(default=False, verbose_name="Macro capable"),
        ),
    ]
