# Generated by Django 5.1.3 on 2024-12-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gear", "0016_alter_body_macro_alter_lens_blades_alter_lens_macro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="body",
            name="camera_type",
            field=models.IntegerField(
                choices=[
                    (0, "Unknown"),
                    (5, "Chamber"),
                    (10, "Chamber Stereo"),
                    (15, "Folding"),
                    (20, "Box"),
                    (25, "Box Stereo"),
                    (30, "Instant"),
                    (35, "Disposable"),
                    (40, "Toy"),
                    (45, "Panoramic"),
                    (47, "Point & Shoot"),
                    (48, "SLR"),
                    (49, "TLR"),
                    (50, "Reflex SLR"),
                    (55, "Reflex TLR"),
                    (60, "Reflex DSLR"),
                    (65, "Digital"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="body",
            name="film_type",
            field=models.IntegerField(
                choices=[
                    (0, "Unknown"),
                    (5, "8mm"),
                    (10, "9.5mm"),
                    (15, "16mm"),
                    (20, "17.5mm"),
                    (25, "28mm"),
                    (30, "35mm"),
                    (35, "70mm"),
                    (40, "110"),
                    (45, "120"),
                    (50, "126"),
                    (55, "127"),
                    (60, "135"),
                    (65, "616"),
                    (70, "628"),
                    (75, "Disc"),
                    (80, "Ektachrome"),
                    (85, "Ektar"),
                    (90, "Kodachrome"),
                    (95, "Eastmancolor"),
                    (100, "Plate"),
                    (105, "Pack-Film"),
                    (110, "Pack-Film 100"),
                    (115, "Pack-Film 100 or 80"),
                    (120, "Pack-Film 80"),
                    (125, "Super 8"),
                    (130, "Single 8"),
                    (135, "Double 8"),
                ],
                default=0,
            ),
        ),
    ]
