clone:
  git:
    image: plugins/git:1
    depth: 50
    tags: true

pipeline:
  restore-cache:
      image: drillster/drone-volume-cache
      restore: true
      mount:
          - .cache
      volumes:
          - /tmp/cache:/cache

  build:
    image: python:3-alpine
    commands:
      - apk add -U postgresql-dev git libffi libffi-dev cmake gcc g++ make pkgconfig
      - pip install --upgrade pip setuptools
      - pip install --cache-dir=/cache flake8
      - pip install --cache-dir=/cache black
      - pip install --cache-dir=/cache -r requirements.txt
      - python setup.py install
      - black --check .
      - flake8 .

  migrations:
    image: python:3-alpine
    commands:
      - apk add -U postgresql-dev git libffi libffi-dev cmake gcc g++ make pkgconfig
      - pip install --upgrade pip setuptools
      - pip install --cache-dir=/cache flake8
      - pip install --cache-dir=/cache black
      - pip install --cache-dir=/cache -r requirements.txt
      - python setup.py install
      - psql -U postgres -h database -w -c 'CREATE DATABASE camgear'
      - cp config.py.sample config.py
      - flask db upgrade

  rebuild-cache:
      image: drillster/drone-volume-cache
      rebuild: true
      mount:
          - .cache
      volumes:
          - /tmp/cache:/cache

  notify:
    image: plugins/slack
    channel: gitea
    secrets:
      - SLACK_WEBHOOK
    when:
      event: [ push, tag, pull_request ]
      status: [ changed, failure, success ]

services:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=camgear_test
