repos:
    - repo: local
      hooks:
          - id: black
            name: black
            language: system
            entry: python3 -m black
            types: [python]
            files: ^api/
          - id: flake8
            name: flake8
            language: system
            entry: flake8
            types: [python]
            files: ^api/
