[tool.black]
line-length = 120
exclude = '''
/(
    \.git
  | \.eggs
  | \.idea
  | \__pycache__
  | venv
  | front
  | controllers/part/static/django-dynamic-formset
  | controllers/part/static/qrcode-generator
)/
'''
skip-numeric-underscore-normalization = true
