# Generated by Django 5.1.3 on 2024-12-03 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("datas", "0001_initial"),
        ("gear", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessoryurl",
            name="body",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accessory_urls",
                to="gear.accessory",
            ),
        ),
        migrations.AddField(
            model_name="bodyurl",
            name="body",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="body_urls",
                to="gear.body",
            ),
        ),
        migrations.AddField(
            model_name="lenseurl",
            name="body",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lens_urls",
                to="gear.lens",
            ),
        ),
        migrations.AddField(
            model_name="system",
            name="manufacturers",
            field=models.ManyToManyField(to="datas.manufacturer"),
        ),
    ]
