# Generated by Django 5.1.3 on 2024-12-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datas", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessoryurl",
            name="private",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bodyurl",
            name="private",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lenseurl",
            name="private",
            field=models.BooleanField(default=False),
        ),
    ]
