# Generated by Django 5.1.3 on 2024-12-05 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datas", "0003_accessoryurl_private_bodyurl_private_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="system",
            name="manufacturers",
        ),
    ]
