# Generated by Django 3.1.8 on 2021-04-26 18:13

import controllers.files.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "file",
                    models.FileField(upload_to="files/", validators=[controllers.files.validators.validate_other]),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "File",
                "verbose_name_plural": "Files",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Picture",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "file",
                    models.ImageField(
                        upload_to="pictures/", validators=[controllers.files.validators.validate_picture]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Picture",
                "verbose_name_plural": "Pictures",
                "ordering": ("id",),
            },
        ),
    ]
