# Generated by Django 3.1.8 on 2021-04-26 18:45

import controllers.files.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gear", "0004_auto_20210426_1845"),
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CameraFile",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "file",
                    models.FileField(upload_to="files/", validators=[controllers.files.validators.validate_other]),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="camera_files", to="gear.camera"
                    ),
                ),
            ],
            options={
                "verbose_name": "File",
                "verbose_name_plural": "Files",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="CameraPicture",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "file",
                    models.ImageField(
                        upload_to="pictures/", validators=[controllers.files.validators.validate_picture]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="camera_pictures", to="gear.camera"
                    ),
                ),
            ],
            options={
                "verbose_name": "Picture",
                "verbose_name_plural": "Pictures",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="LensFile",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "file",
                    models.FileField(upload_to="files/", validators=[controllers.files.validators.validate_other]),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lens",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="lens_files", to="gear.lens"
                    ),
                ),
            ],
            options={
                "verbose_name": "File",
                "verbose_name_plural": "Files",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="LensPicture",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "file",
                    models.ImageField(
                        upload_to="pictures/", validators=[controllers.files.validators.validate_picture]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lens",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="lens_pictures", to="gear.lens"
                    ),
                ),
            ],
            options={
                "verbose_name": "Picture",
                "verbose_name_plural": "Pictures",
                "ordering": ("id",),
            },
        ),
        migrations.DeleteModel(
            name="File",
        ),
        migrations.DeleteModel(
            name="Picture",
        ),
    ]
