# Generated by Django 3.1.8 on 2021-04-26 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_auto_20210426_1845"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="camerafile",
            options={"ordering": ("id",), "verbose_name": "Camera File", "verbose_name_plural": "Camera Files"},
        ),
        migrations.AlterModelOptions(
            name="camerapicture",
            options={"ordering": ("id",), "verbose_name": "Camera Picture", "verbose_name_plural": "Camera Pictures"},
        ),
        migrations.AlterModelOptions(
            name="lensfile",
            options={"ordering": ("id",), "verbose_name": "Lens File", "verbose_name_plural": "Lens Files"},
        ),
        migrations.AlterModelOptions(
            name="lenspicture",
            options={"ordering": ("id",), "verbose_name": "Lens Picture", "verbose_name_plural": "Lens Pictures"},
        ),
    ]
