# Generated by Django 3.1.8 on 2021-04-26 19:11

import controllers.files.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gear", "0005_accessory"),
        ("files", "0003_auto_20210426_1902"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessoryPicture",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "file",
                    models.ImageField(
                        upload_to="pictures/", validators=[controllers.files.validators.validate_picture]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lens",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accessory_pictures",
                        to="gear.accessory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accessory Picture",
                "verbose_name_plural": "Accessory Pictures",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="AccessoryFile",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "file",
                    models.FileField(upload_to="files/", validators=[controllers.files.validators.validate_other]),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lens",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="accessory_files", to="gear.accessory"
                    ),
                ),
            ],
            options={
                "verbose_name": "Accessory File",
                "verbose_name_plural": "Accessory Files",
                "ordering": ("id",),
            },
        ),
    ]
