# Generated by Django 3.1.4 on 2021-04-26 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'Unknown'), (5, 'Very Good'), (10, 'Good'), (15, 'Ok, scratches'), (20, 'Not so ok'), (25, 'Cracks'), (30, 'Partly working'), (35, 'Not working'), (40, 'Lost'), (45, 'Stolen')], default=0)),
                ('state_notes', models.CharField(blank=True, max_length=255)),
                ('model', models.CharField(blank=True, max_length=255)),
                ('model_notes', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('serial', models.CharField(blank=True, max_length=255)),
                ('focale_min', models.IntegerField(default=0)),
                ('focale_max', models.IntegerField(default=0)),
                ('min_aperture', models.FloatField(default=0)),
                ('max_aperture', models.FloatField(default=0)),
                ('lens_type', models.IntegerField(choices=[(0, 'Unknown'), (5, 'Wide Angle'), (10, 'Standard'), (15, 'Zoom'), (20, 'Telephoto')], default=0)),
                ('macro', models.BooleanField(default=True)),
                ('macro_length', models.IntegerField(default=0)),
                ('filter_diameter', models.IntegerField(default=0)),
                ('blades', models.BooleanField(default=True)),
                ('angle', models.FloatField(blank=True, default=0)),
                ('focus', models.IntegerField(choices=[(0, 'Unknown'), (5, 'Manual'), (10, 'Automatic'), (15, 'Fixed'), (20, 'Auto/Man')], default=0)),
                ('focus_length', models.IntegerField(blank=True, default=0)),
                ('weight', models.IntegerField(default=0)),
                ('length', models.IntegerField(default=0)),
                ('private', models.BooleanField(default=False)),
                ('can_be_sold', models.BooleanField(default=False)),
                ('url1', models.URLField(blank=True)),
                ('url2', models.URLField(blank=True)),
                ('url3', models.URLField(blank=True)),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gear.manufacturer')),
                ('mount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gear.mount')),
            ],
        ),
    ]
