# Generated by Django 3.1.8 on 2021-04-26 18:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
        ("gear", "0002_lens"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lens",
            options={"verbose_name_plural": "Lenses"},
        ),
        migrations.AddField(
            model_name="camera",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="camera",
            name="files",
            field=models.ManyToManyField(to="files.File"),
        ),
        migrations.AddField(
            model_name="camera",
            name="pictures",
            field=models.ManyToManyField(to="files.Picture"),
        ),
        migrations.AddField(
            model_name="camera",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="lens",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lens",
            name="files",
            field=models.ManyToManyField(to="files.File"),
        ),
        migrations.AddField(
            model_name="lens",
            name="pictures",
            field=models.ManyToManyField(to="files.Picture"),
        ),
        migrations.AddField(
            model_name="lens",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
