# Generated by Django 3.1.8 on 2021-04-26 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gear", "0004_auto_20210426_1845"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accessory",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "state",
                    models.IntegerField(
                        choices=[
                            (0, "Unknown"),
                            (5, "Very Good"),
                            (10, "Good"),
                            (15, "Ok, scratches"),
                            (20, "Not so ok"),
                            (25, "Cracks"),
                            (30, "Partly working"),
                            (35, "Not working"),
                            (40, "Lost"),
                            (45, "Stolen"),
                        ],
                        default=0,
                    ),
                ),
                ("state_notes", models.CharField(blank=True, max_length=255)),
                ("model", models.CharField(blank=True, max_length=255)),
                ("model_notes", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("serial", models.CharField(blank=True, max_length=255)),
                ("batteries", models.CharField(blank=True, max_length=255)),
                ("private", models.BooleanField(default=False)),
                ("can_be_sold", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url1", models.URLField(blank=True)),
                ("url2", models.URLField(blank=True)),
                ("url3", models.URLField(blank=True)),
                (
                    "manufacturer",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="gear.manufacturer"),
                ),
                ("mount", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="gear.mount")),
            ],
        ),
    ]
