# Generated by Django 3.1.8 on 2021-04-27 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gear", "0006_auto_20210426_2020"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessory",
            name="user",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="camera",
            name="user",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="lens",
            name="user",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="accessory",
            name="serial",
            field=models.CharField(blank=True, max_length=255, verbose_name="Serial (private)"),
        ),
        migrations.AlterField(
            model_name="camera",
            name="auto_expo",
            field=models.BooleanField(default=True, verbose_name="Auto exposure"),
        ),
        migrations.AlterField(
            model_name="camera",
            name="blades",
            field=models.BooleanField(default=True, verbose_name="Using blades"),
        ),
        migrations.AlterField(
            model_name="camera",
            name="filter_diameter",
            field=models.IntegerField(default=0, verbose_name="Filter Dia. (mm)"),
        ),
        migrations.AlterField(
            model_name="camera",
            name="focale_max",
            field=models.IntegerField(default=0, verbose_name="Focale max (mm)"),
        ),
        migrations.AlterField(
            model_name="camera",
            name="focale_min",
            field=models.IntegerField(default=0, verbose_name="Focale min (mm)"),
        ),
        migrations.AlterField(
            model_name="camera",
            name="focus",
            field=models.IntegerField(
                choices=[(0, "Unknown"), (5, "Manual"), (10, "Automatic"), (15, "Fixed"), (20, "Auto/Man")],
                default=0,
                verbose_name="Focus mode",
            ),
        ),
        migrations.AlterField(
            model_name="camera",
            name="focus_length",
            field=models.IntegerField(default=0, verbose_name="Min focus (cm)"),
        ),
        migrations.AlterField(
            model_name="camera",
            name="iso_max",
            field=models.IntegerField(default=0, verbose_name="ISO max"),
        ),
        migrations.AlterField(
            model_name="camera",
            name="iso_min",
            field=models.IntegerField(default=0, verbose_name="ISO min"),
        ),
        migrations.AlterField(
            model_name="camera",
            name="length",
            field=models.IntegerField(default=0, verbose_name="Length (cm)"),
        ),
        migrations.AlterField(
            model_name="camera",
            name="macro",
            field=models.BooleanField(default=True, verbose_name="Macro capable"),
        ),
        migrations.AlterField(
            model_name="camera",
            name="macro_length",
            field=models.IntegerField(default=0, verbose_name="Min macro (cm)"),
        ),
        migrations.AlterField(
            model_name="camera",
            name="serial",
            field=models.CharField(blank=True, max_length=255, verbose_name="Serial (private)"),
        ),
        migrations.AlterField(
            model_name="camera",
            name="weight",
            field=models.IntegerField(default=0, verbose_name="Weight (g)"),
        ),
        migrations.AlterField(
            model_name="lens",
            name="blades",
            field=models.BooleanField(default=True, verbose_name="Using blades"),
        ),
        migrations.AlterField(
            model_name="lens",
            name="filter_diameter",
            field=models.IntegerField(default=0, verbose_name="Filter Dia. (mm)"),
        ),
        migrations.AlterField(
            model_name="lens",
            name="focale_max",
            field=models.IntegerField(default=0, verbose_name="Focale max (mm)"),
        ),
        migrations.AlterField(
            model_name="lens",
            name="focale_min",
            field=models.IntegerField(default=0, verbose_name="Focale min (mm)"),
        ),
        migrations.AlterField(
            model_name="lens",
            name="focus",
            field=models.IntegerField(
                choices=[(0, "Unknown"), (5, "Manual"), (10, "Automatic"), (15, "Fixed"), (20, "Auto/Man")],
                default=0,
                verbose_name="Focus mode",
            ),
        ),
        migrations.AlterField(
            model_name="lens",
            name="focus_length",
            field=models.IntegerField(default=0, verbose_name="Min focus (cm)"),
        ),
        migrations.AlterField(
            model_name="lens",
            name="length",
            field=models.IntegerField(default=0, verbose_name="Length (cm)"),
        ),
        migrations.AlterField(
            model_name="lens",
            name="macro",
            field=models.BooleanField(default=True, verbose_name="Macro capable"),
        ),
        migrations.AlterField(
            model_name="lens",
            name="macro_length",
            field=models.IntegerField(default=0, verbose_name="Min macro (cm)"),
        ),
        migrations.AlterField(
            model_name="lens",
            name="mount",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="gear.mount"
            ),
        ),
        migrations.AlterField(
            model_name="lens",
            name="serial",
            field=models.CharField(blank=True, max_length=255, verbose_name="Serial (private)"),
        ),
        migrations.AlterField(
            model_name="lens",
            name="weight",
            field=models.IntegerField(default=0, verbose_name="Weight (g)"),
        ),
    ]
