# Generated by Django 3.1.8 on 2021-04-27 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gear", "0007_auto_20210427_0504"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessory",
            name="mount",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="gear.mount"
            ),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="mount",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
