"""Add description to each model

Revision ID: 4d95d3ffc004
Revises: 3676351f2e38
Create Date: 2018-11-30 09:15:49.967712

"""

# revision identifiers, used by Alembic.
revision = "4d95d3ffc004"
down_revision = "3676351f2e38"

from alembic import op  # noqa: E402
import sqlalchemy as sa  # noqa: E402


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("camera", sa.Column("description", sa.String(length=255), nullable=True))
    op.add_column("lense", sa.Column("description", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("lense", "description")
    op.drop_column("camera", "description")
    # ### end Alembic commands ###
