"""Add private field

Revision ID: cf61152b1cd9
Revises: 4d95d3ffc004
Create Date: 2018-11-30 09:40:03.271068

"""

# revision identifiers, used by Alembic.
revision = 'cf61152b1cd9'
down_revision = '4d95d3ffc004'

from alembic import op  # noqa: E402
import sqlalchemy as sa  # noqa: E402


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accessory', sa.Column('private', sa.Boolean(), nullable=True))
    op.add_column('camera', sa.Column('private', sa.Boolean(), nullable=True))
    op.add_column('lense', sa.Column('private', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lense', 'private')
    op.drop_column('camera', 'private')
    op.drop_column('accessory', 'private')
    # ### end Alembic commands ###
