"""Fix nullables

Revision ID: 093c0f1e64fe
Revises: cf61152b1cd9
Create Date: 2018-11-30 14:47:27.078995

"""

# revision identifiers, used by Alembic.
revision = "093c0f1e64fe"
down_revision = "cf61152b1cd9"

from alembic import op  # noqa: E402
import sqlalchemy as sa  # noqa: E402


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("camera", schema=None) as batch_op:
        batch_op.alter_column("filter_diameter", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("focus_length", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("macro_length", existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table("lense", schema=None) as batch_op:
        batch_op.alter_column("filter_diameter", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("focale", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("focus_length", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("length", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("macro_length", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("weight", existing_type=sa.INTEGER(), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lense", schema=None) as batch_op:
        batch_op.alter_column("weight", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("macro_length", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("length", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("focus_length", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("focale", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("filter_diameter", existing_type=sa.INTEGER(), nullable=False)

    with op.batch_alter_table("camera", schema=None) as batch_op:
        batch_op.alter_column("macro_length", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("focus_length", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("filter_diameter", existing_type=sa.INTEGER(), nullable=False)

    # ### end Alembic commands ###
