"""Add batteries for accessories

Revision ID: a5506eaab316
Revises: 093c0f1e64fe
Create Date: 2018-11-30 15:17:02.223261

"""

# revision identifiers, used by Alembic.
revision = "a5506eaab316"
down_revision = "093c0f1e64fe"

from alembic import op  # noqa: E402
import sqlalchemy as sa  # noqa: E402


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("accessory", schema=None) as batch_op:
        batch_op.add_column(sa.Column("batteries", sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("accessory", schema=None) as batch_op:
        batch_op.drop_column("batteries")

    # ### end Alembic commands ###
