"""Split focale in focale _min and _max

Revision ID: 87dd2d1d6a96
Revises: cbeca940d198
Create Date: 2018-12-06 17:06:11.111270

"""

# revision identifiers, used by Alembic.
revision = "87dd2d1d6a96"
down_revision = "cbeca940d198"

from alembic import op  # noqa: E402
import sqlalchemy as sa  # noqa: E402


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("camera", schema=None) as batch_op:
        batch_op.add_column(sa.Column("focale_max", sa.Integer(), nullable=True, default=0))

    with op.batch_alter_table("lense", schema=None) as batch_op:
        batch_op.add_column(sa.Column("focale_max", sa.Integer(), nullable=True, default=0))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lense", schema=None) as batch_op:
        batch_op.drop_column("focale_max")

    with op.batch_alter_table("camera", schema=None) as batch_op:
        batch_op.drop_column("focale_max")

    # ### end Alembic commands ###
