# Generated by Django 5.1.3 on 2024-12-03 16:10

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gear", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessorySerial",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("gear.accessory",),
        ),
        migrations.CreateModel(
            name="BodySerial",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("gear.body",),
        ),
        migrations.CreateModel(
            name="LensSerial",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("gear.lens",),
        ),
    ]
