# Generated by Django 3.1.8 on 2021-04-27 05:04

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gear", "0007_auto_20210427_0504"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessorySerial",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("gear.accessory",),
        ),
        migrations.CreateModel(
            name="CameraSerial",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("gear.camera",),
        ),
        migrations.CreateModel(
            name="LensSerial",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("gear.lens",),
        ),
    ]
