# Generated by Django 5.1.3 on 2024-12-03 16:10

import django.db.models.deletion
import files.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gear", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessoryFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "file",
                    models.FileField(upload_to="files/", validators=[files.validators.validate_other]),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lens",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accessory_files",
                        to="gear.accessory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accessory File",
                "verbose_name_plural": "Accessory Files",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="AccessoryPicture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "file",
                    models.ImageField(
                        upload_to="pictures/",
                        validators=[files.validators.validate_picture],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lens",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accessory_pictures",
                        to="gear.accessory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accessory Picture",
                "verbose_name_plural": "Accessory Pictures",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="BodyFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "file",
                    models.FileField(upload_to="files/", validators=[files.validators.validate_other]),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "body",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="body_files",
                        to="gear.body",
                    ),
                ),
            ],
            options={
                "verbose_name": "Body File",
                "verbose_name_plural": "Body Files",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="BodyPicture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "file",
                    models.ImageField(
                        upload_to="pictures/",
                        validators=[files.validators.validate_picture],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "body",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="body_pictures",
                        to="gear.body",
                    ),
                ),
            ],
            options={
                "verbose_name": "Body Picture",
                "verbose_name_plural": "Body Pictures",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="LensFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "file",
                    models.FileField(upload_to="files/", validators=[files.validators.validate_other]),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lens",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lens_files",
                        to="gear.lens",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lens File",
                "verbose_name_plural": "Lens Files",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="LensPicture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "file",
                    models.ImageField(
                        upload_to="pictures/",
                        validators=[files.validators.validate_picture],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lens",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lens_pictures",
                        to="gear.lens",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lens Picture",
                "verbose_name_plural": "Lens Pictures",
                "ordering": ("id",),
            },
        ),
    ]
