# Generated by Django 5.1.3 on 2024-12-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessoryfile",
            name="private",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="accessorypicture",
            name="private",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bodyfile",
            name="private",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bodypicture",
            name="private",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lensfile",
            name="private",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lenspicture",
            name="private",
            field=models.BooleanField(default=False),
        ),
    ]
